namespace NestyStay.Infrastructure.Persistence;

public sealed record BackendTableSpec(string Area, string TableName, string Purpose);

public static class SchemaCatalog
{
    public static IReadOnlyList<BackendTableSpec> Tables { get; } =
    [
        new("Identity", "users", "Accounts, Auth0 subjects, profile, 2FA, status."),
        new("Identity", "roles", "System role catalog for all planned portals."),
        new("Identity", "user_role_assignment", "User role membership."),
        new("Identity", "user_consent", "Privacy, eKYC, payment, messaging, insurance consent."),
        new("Admin", "audit_log", "Sensitive/admin change trail."),
        new("Verification", "verification_check", "eKYC checks across users, properties, providers, officers, guests."),
        new("Verification", "verification_event", "Provider webhook payload snapshots."),
        new("Verification", "identity_document", "Encrypted identity document metadata."),
        new("Properties", "property", "Host listing and verification/insurance/cancellation state."),
        new("Properties", "property_unit", "Multi-unit and community unit records."),
        new("Properties", "property_media", "Storage-backed property media."),
        new("Properties", "property_availability", "Calendar blocks and booking holds."),
        new("Properties", "property_pricing_rule", "Nightly rate, discounts, overrides."),
        new("Properties", "property_founding_benefit", "Platinum, Gold, Silver, Standard transfer rules."),
        new("Properties", "property_transfer_request", "Founding benefit transfer approval workflow."),
        new("Bookings", "booking", "Guest stay record and verification/payment status."),
        new("Bookings", "booking_guest", "Additional guests."),
        new("Bookings", "booking_price_line", "Refundable and non-refundable fee lines."),
        new("Bookings", "booking_payment_schedule", "Full and split payment schedules."),
        new("Bookings", "booking_status_event", "Immutable booking timeline."),
        new("Bookings", "booking_cancellation", "Cancellation and refund details."),
        new("Bookings", "booking_dispute", "Dispute evidence and resolution."),
        new("Pricing", "pricebook_entry", "Configurable pricing, fees, commissions, campaigns."),
        new("Pricing", "campaign", "Founding/promotional campaigns."),
        new("Pricing", "campaign_enrollment", "Subject campaign membership."),
        new("Badges", "badge_definition", "Badge unlock catalog."),
        new("Badges", "badge_assignment", "Badge state per subject."),
        new("Badges", "badge_renewal", "Badge renewal reminders/payments."),
        new("Badges", "rating_policy", "Rating enforcement thresholds."),
        new("Payments", "payment_account", "Gateway accounts for payouts."),
        new("Payments", "payment_intent_record", "Stripe/PayPal checkout intents."),
        new("Payments", "payment_transaction", "Captures/refunds/transfers."),
        new("Payments", "escrow_hold", "Wellness/provider escrow lifecycle."),
        new("Payments", "payout", "Recipient payouts."),
        new("Payments", "subscription", "Badges, PM, association, insurance billing."),
        new("Payments", "invoice", "Invoice headers."),
        new("Payments", "invoice_line", "Invoice line items."),
        new("Messaging", "conversation_thread", "Booking/community/provider/gate threads."),
        new("Messaging", "message", "Retained messages."),
        new("Access", "qr_access_code", "Booking/unit/community QR access."),
        new("Access", "qr_scan_log", "Every QR scan result."),
        new("Access", "visitor_log", "Visitor and delivery logs."),
        new("Directories", "service_provider_profile", "Custodian/trades profiles."),
        new("Directories", "service_provider_sponsorship", "Verified host sponsorship."),
        new("Directories", "service_job", "Provider jobs and quotes."),
        new("Directories", "local_business", "Brick-and-mortar business profiles."),
        new("Directories", "directory_review", "Verified directory reviews."),
        new("Directories", "directory_commission", "Provider/business commission rules."),
        new("Wellness", "officer", "Active JCF officer eligibility and private ID."),
        new("Wellness", "officer_id_history", "Annual NestyStay ID reset history."),
        new("Wellness", "wellness_visit_type_definition", "Eight visit type catalog."),
        new("Wellness", "wellness_visit", "Scheduled wellness jobs."),
        new("Wellness", "wellness_report", "Photo reports."),
        new("Wellness", "wellness_badge", "Property wellness badge validity."),
        new("Wellness", "wellness_escrow_event", "Wellness escrow status events."),
        new("PropertyManagement", "community", "Buildings/complexes and governance mode."),
        new("PropertyManagement", "community_membership", "Owner, tenant, manager, executive access."),
        new("PropertyManagement", "owner_unit", "Unit ownership."),
        new("PropertyManagement", "maintenance_request", "Maintenance workflow."),
        new("PropertyManagement", "utility_bill", "Utility upload and allocation."),
        new("PropertyManagement", "manager_statement", "Owner/community statements."),
        new("PropertyManagement", "arrears_record", "Overdue maintenance fees."),
        new("PropertyManagement", "community_announcement", "Bulletin board."),
        new("PropertyManagement", "staff_assignment", "Staff schedule."),
        new("AssociationManagement", "meeting", "Meeting notice/agenda/archive."),
        new("AssociationManagement", "meeting_document", "Meeting documents."),
        new("AssociationManagement", "financial_statement_version", "Required statement timeline versions."),
        new("AssociationManagement", "vote", "Encrypted individual vote payload."),
        new("AssociationManagement", "vote_result", "Aggregate result only."),
        new("AssociationManagement", "proxy", "Proxy cutoff and eligibility."),
        new("AssociationManagement", "bid_opening", "Sealed bid reveal."),
        new("AssociationManagement", "association_storage_plan", "Free/Starter/Pro/Elite plans."),
        new("AssociationManagement", "document_retention_rule", "Retention enforcement."),
        new("Documents", "storage_object", "Provider-agnostic object metadata."),
        new("Documents", "document_vault_item", "Community/property/provider vault records."),
        new("Notifications", "notification_template", "Email/SMS/push templates."),
        new("Notifications", "notification_queue_item", "Queued/sent/failed notifications."),
        new("Integrations", "provider_config", "Provider selection and encrypted config references."),
        new("Integrations", "provider_event", "Raw provider webhook event storage."),
        new("Integrations", "integration_failover", "Provider switch audit trail.")
    ];
}
