import { useState, type ReactNode } from "react";
import { ChevronDown, ChevronUp, Search } from "lucide-react";
import { AppLink } from "../../components/AppLink";
import { PublicFooter } from "../../components/layout/PublicShell";
import { PatoisPhrase } from "../../lib/patois";
import { LEGAL_DETAILS } from "../../lib/legal";

interface LegalHelpPagesProps { view: string; }

function PolicySection({ title, children }: { title: string; children: ReactNode }) {
  return <section className="grid gap-2"><h2 className="m-0 font-display text-2xl font-medium text-ink">{title}</h2><div className="grid gap-2 text-[14px] leading-6 text-gray-700">{children}</div></section>;
}

function LegalMeta() { return <p className="m-0 text-xs text-sand-600">Last updated {LEGAL_DETAILS.lastUpdated} · Website: {LEGAL_DETAILS.website}</p>; }

function LegalDocument({ kind }: { kind: "terms" | "privacy" | "cookies" | "refund-policy" }) {
  const title = kind === "terms" ? "Terms of Service" : kind === "privacy" ? "Privacy Policy" : kind === "cookies" ? "Cookie Policy" : "Refund Policy";
  return <><div className="page-container container py-6" data-testid={`${kind}-page`} id={`PUB-${kind.toUpperCase()}`}>
    <header className="page-header mb-6"><span className="badge badge-sun">LEGAL</span><h1 data-route-heading="true">{title}</h1><PatoisPhrase phrase="Clear terms. Clear choices." translation="Read how NestyStay handles bookings, information, cookies, and refunds." /><LegalMeta /></header>
    <article className="card-box max-w-4xl space-y-6 text-sm leading-relaxed">
      {kind === "privacy" && <>
        <PolicySection title="Who operates this site"><p>NestyStay operates this website and booking platform at nestystay.net. Current public contact details are WhatsApp {LEGAL_DETAILS.supportPhone} and the <AppLink className="font-semibold text-deep-hover underline" href="/contact">Contact page</AppLink>. The operator must publish its registered legal name, service address, privacy email, and data-protection contact before production launch.</p></PolicySection>
        <PolicySection title="Information we collect"><p>We collect only information needed to provide the service: account and contact details; booking, stay, host, property, message, support, and payment records; identity-verification status and provider references; and security, device, and technical data needed to protect the service. Payment-card details are handled by Stripe rather than stored as full card numbers by NestyStay.</p></PolicySection>
        <PolicySection title="Why we use it"><p>We use information to create and secure accounts, process searches and bookings, communicate about a stay, provide identity and payment workflows, prevent abuse, meet legal obligations, resolve disputes, and maintain reliable systems. Optional analytics or marketing will be used only after consent. We do not sell personal information.</p></PolicySection>
        <PolicySection title="Service providers and sharing"><p>Information may be shared with the host or guest involved in a booking, and with providers required for the requested service, such as Stripe for payments and Identity, Brevo or Zoho for configured communications, hosting/storage providers, and map or sign-in providers when you use those features. Providers may process information outside Jamaica; the operator must confirm appropriate contracts and transfer safeguards before production.</p></PolicySection>
        <PolicySection title="Identity verification"><p>Where a booking or host workflow requires verification, Stripe Identity may process identity information under its own privacy terms. NestyStay receives the verification result and relevant references needed to operate the booking, not a promise that every identity check is approved. Read Stripe&apos;s <a className="font-semibold text-deep-hover underline" href="https://stripe.com/legal/privacy-center" rel="noreferrer" target="_blank">Privacy Center</a> and <a className="font-semibold text-deep-hover underline" href="https://docs.stripe.com/identity/explaining-identity" rel="noreferrer" target="_blank">Identity explanation</a>.</p></PolicySection>
        <PolicySection title="Retention and your choices"><p>We retain information only for as long as needed for the stated purpose, a live account or booking, security, disputes, accounting, or a legal obligation. The operator must publish a documented retention schedule before launch. Subject to applicable law, you may request access, correction, deletion, restriction, objection, or a copy of your information, and withdraw consent for optional processing. Contact us first; complaints may also be directed to Jamaica&apos;s Office of the Information Commissioner.</p></PolicySection>
        <PolicySection title="Security, children, and updates"><p>We use reasonable technical and organisational safeguards, but no internet service can promise absolute security. Do not send identity documents or payment details through ordinary chat or contact forms. The service is not directed to children; the operator must confirm the minimum age and guardian rules with counsel. We may update this notice and will show the new date.</p></PolicySection>
      </>}
      {kind === "terms" && <>
        <PolicySection title="Using NestyStay"><p>NestyStay provides a marketplace and related tools for guests, hosts, and service providers. Unless the booking expressly says otherwise, NestyStay is not the owner, operator, insurer, or manager of a listed property. Listing details, availability, fees, house rules, cancellation terms, and host information must be reviewed before a booking request is submitted.</p></PolicySection>
        <PolicySection title="Accounts and acceptable use"><p>Provide accurate information, keep credentials secure, and use only accounts you are authorised to use. Do not impersonate another person, submit misleading property or identity information, misuse messages or reviews, bypass security, discriminate unlawfully, or use the platform for unsafe or illegal activity. We may restrict or close access where necessary for safety, fraud prevention, legal compliance, or breach of these terms.</p></PolicySection>
        <PolicySection title="Bookings, verification, and payment"><p>A booking request may remain pending until the host and any required verification steps are complete. A verification or payment status shown by the platform is the status returned by the relevant workflow; it is not a guarantee of a person, property, event, or outcome. Stripe processes payment details and may require additional authentication. A booking confirmation, rejection, cancellation, refund, or payment failure will be shown in the booking record.</p></PolicySection>
        <PolicySection title="Prices, cancellations, and refunds"><p>Prices and fees are shown at checkout when available. The property&apos;s displayed cancellation policy and the <AppLink className="font-semibold text-deep-hover underline" href="/refund-policy">Refund Policy</AppLink> control applicable refunds, subject to applicable law and any specific booking terms. Do not rely on a general refund promise where the booking record states a different policy.</p></PolicySection>
        <PolicySection title="Content, reviews, and communication"><p>You remain responsible for content you submit and must have the rights to use it. You grant NestyStay permission to host and display it only as needed to operate the service. Reviews should describe genuine experiences and may be moderated. Keep booking-related communication on the platform when possible.</p></PolicySection>
        <PolicySection title="Legal details"><p>These terms need the operator&apos;s registered legal name, address, governing law, dispute process, liability wording, insurance wording, and notice email before production. Those details must be approved by the business and qualified counsel; they are intentionally not invented here.</p></PolicySection>
      </>}
      {kind === "cookies" && <>
        <PolicySection title="What we use"><p>Essential session, security, and preference storage is required for sign-in, protected actions, and remembering your cookie choice. The current frontend contains no installed analytics SDK or analytics tag, and optional analytics is disabled by default.</p></PolicySection>
        <PolicySection title="Third-party technologies"><p>Stripe.js and Stripe Identity may create or read provider-controlled cookies or device signals during payment and verification. Google Fonts, Google sign-in, OpenStreetMap map embeds, and remote image hosts can receive technical request data when their feature is used. Their own terms and privacy notices apply. The operator should self-host fonts and use a documented image licence register before production where appropriate.</p></PolicySection>
        <PolicySection title="Your choice"><p>Choose “Reject optional” to keep optional analytics disabled, or “Allow optional” if it is later introduced and you consent to it. You can reopen the choice at any time with Cookie settings in the footer. Essential storage cannot be disabled through this control because the core account and security functions would not work.</p></PolicySection>
        <PolicySection title="Current status"><p>No optional analytics or advertising cookies are loaded by this build. If tracking is added later, it must be documented here, blocked until consent where required, and accompanied by an updated privacy notice.</p></PolicySection>
      </>}
      {kind === "refund-policy" && <>
        <PolicySection title="How refunds are decided"><p>Refund eligibility is determined by the cancellation and refund terms shown for the specific booking, together with the reason and status recorded in the platform. A host rejection, platform cancellation, payment failure, identity-verification failure, or guest cancellation may have different outcomes. The booking record is the source of truth; NestyStay does not promise a single universal refund amount.</p></PolicySection>
        <PolicySection title="How refunds are sent"><p>Approved refunds are returned through the payment method used for the booking where possible. Stripe controls payment processing and bank-card posting times, so a refund may take additional business days to appear. NestyStay may need to review duplicate charges, disputes, fraud indicators, or provider errors before releasing funds.</p></PolicySection>
        <PolicySection title="What to do"><p>Review the booking&apos;s cancellation policy, receipt, and status first. For a discrepancy, contact NestyStay through the <AppLink className="font-semibold text-deep-hover underline" href="/contact">Contact page</AppLink> or WhatsApp {LEGAL_DETAILS.supportPhone} with the booking reference. Do not include full card numbers or identity documents.</p></PolicySection>
        <PolicySection title="Before production"><p>The operator must confirm the applicable Jamaican consumer, tax, payments, and contract requirements, the legal entity and address, the service-fee treatment, and the escalation timeline with qualified counsel before accepting live bookings.</p></PolicySection>
      </>}
    </article>
  </div><PublicFooter /></>;
}

export function LegalHelpPages({ view }: LegalHelpPagesProps) {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [searchQuery, setSearchQuery] = useState("");
  const faqs = [
    { q: "How does guest identity verification work?", a: "When a booking requires it, the platform starts the configured Stripe Identity workflow. The booking status will show whether verification is processing, approved, failed, or needs attention." },
    { q: "What protection or insurance is included?", a: "Coverage is not universal. Review the individual property and booking terms for any protection information before booking; do not assume a policy or benefit unless it is shown in that booking." },
    { q: "Which cancellation policy applies?", a: "The cancellation and refund terms displayed for the specific property and booking apply. Review them at checkout and keep the booking record for reference." },
  ];
  if (["terms", "privacy", "cookies", "refund-policy"].includes(view)) return <LegalDocument kind={view as "terms" | "privacy" | "cookies" | "refund-policy"} />;
  if (view === "contact") return <div className="mx-auto flex max-w-[640px] flex-col gap-5 px-6 py-12 font-sans text-ink" id="PUB-CONTACT"><h1 className="m-0 font-display text-[clamp(30px,3.4vw,40px)] font-normal" data-route-heading="true">How wi can help <em className="italic text-deep-hover">yuh?</em></h1><p className="m-0 text-[14.5px] text-gray-600">Reach the NestyStay team through a channel listed below. Please do not send passwords, full card numbers, or identity documents.</p><div className="flex flex-col gap-3 rounded-card border border-sand-border bg-cream p-[22px] text-[14.5px]"><a className="inline-flex min-h-12 items-center gap-2.5 self-start rounded-pill bg-success-tint px-[22px] font-bold text-success-text" href={LEGAL_DETAILS.whatsappUrl}>WhatsApp: {LEGAL_DETAILS.supportPhone}</a><div className="text-gray-600">{LEGAL_DETAILS.website} · response times vary by request and provider availability.</div></div></div>;
  if (view === "maintenance") return <div className="flex min-h-[60vh] flex-col items-center justify-center gap-4 px-6 py-16 text-center font-sans text-ink" id="PUB-MAINT"><h1 className="m-0 font-display text-[clamp(32px,4vw,44px)] font-normal" data-route-heading="true">Wi Soon Come!</h1><p className="m-0 max-w-[420px] text-[14.5px] text-gray-600">We&apos;ll be right back — NestyStay is down for scheduled maintenance.</p><a className="inline-flex min-h-11 items-center text-[13.5px] font-semibold text-deep-hover" href={LEGAL_DETAILS.whatsappUrl}>Urgent? WhatsApp {LEGAL_DETAILS.supportPhone}</a></div>;
  if (view === "help" || view === "faq") {
    const visibleFaqs = faqs.filter((faq) => `${faq.q} ${faq.a}`.toLowerCase().includes(searchQuery.toLowerCase()));
    return <div className="page-container container py-6" data-testid="pub-12-help" id="PUB-12"><header className="page-header mb-6 text-center"><span className="badge badge-sun">PUB-12</span><h1 data-route-heading="true">Help Center &amp; FAQs</h1><PatoisPhrase phrase="How Can We Help Yuh?" translation="Find answers about bookings, verification, payments, and policies." /><div className="search-box relative mx-auto my-4 max-w-md"><Search aria-hidden="true" className="absolute left-3 top-3 text-gray-400" size={18} /><label className="sr-only" htmlFor="help-search">Search help topics</label><input className="input-control pl-10" id="help-search" placeholder="Search help topics..." value={searchQuery} onChange={(event) => setSearchQuery(event.target.value)} /></div></header><div className="mx-auto max-w-2xl space-y-3">{visibleFaqs.length === 0 && <p className="text-center text-sm text-gray-600">No help topics match that search.</p>}{visibleFaqs.map((faq) => { const idx = faqs.indexOf(faq); const expanded = openFaq === idx; return <section className="card-box" key={faq.q}><h2 className="m-0"><button aria-controls={`faq-answer-${idx}`} aria-expanded={expanded} className="flex min-h-11 w-full items-center justify-between gap-4 text-left text-lg font-bold" onClick={() => setOpenFaq(expanded ? null : idx)} type="button"><span>{faq.q}</span>{expanded ? <ChevronUp aria-hidden="true" size={18} /> : <ChevronDown aria-hidden="true" size={18} />}</button></h2>{expanded && <p className="mt-3 text-sm subtext" id={`faq-answer-${idx}`}>{faq.a}</p>}</section>; })}</div></div>;
  }
  if (view === "about") return <div className="page-container container py-6" id="PUB-09"><header className="page-header mb-6"><span className="badge badge-sun">ABOUT</span><h1 data-route-heading="true">About NestyStay Jamaica</h1><PatoisPhrase phrase="Stay close to home." translation="A booking platform for stays and local connections." /></header><article className="card-box max-w-3xl space-y-4 text-sm leading-6 text-gray-700"><p>NestyStay helps guests discover stays and gives hosts tools to publish properties, manage reservations, and communicate with guests.</p><p>Listing badges and verification statuses describe the platform record at the time shown. They are not a promise that a property, host, or service is risk-free.</p></article></div>;
  return <div className="page-container container py-6" id="PUB-10"><header className="page-header mb-6"><span className="badge badge-sun">TRUST</span><h1 data-route-heading="true">Trust, Safety &amp; Security</h1><PatoisPhrase phrase="Clear information builds trust." translation="Use the listing, booking, verification, and support records to make informed decisions." /></header><article className="card-box max-w-3xl space-y-4 text-sm leading-6 text-gray-700"><p>Use in-platform messages, review the property details and cancellation terms, and report concerns through the available support route. Identity and payment workflows are provided through configured service providers.</p><p>No badge or verification label replaces your own judgement or emergency services. For immediate danger in Jamaica, call 119.</p></article></div>;
}
