// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NestyStay.Infrastructure.Persistence;

#nullable disable

namespace NestyStay.Infrastructure.Persistence.Migrations;

[DbContext(typeof(NestyStayDbContext))]
[Migration("20260910120000_AddPropertyManagerP0Foundation")]
partial class AddPropertyManagerP0Foundation
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The SQL migration is additive and intentionally creates only the P0
        // tables. The current context model remains the source of truth for
        // future generated migrations.
    }
}
