import { expect, test, type APIRequestContext, type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";

const isoDay = (offset: number) => { const date = new Date(); date.setUTCDate(date.getUTCDate() + offset); return date.toISOString().slice(0, 10); };

async function prepare(api: APIRequestContext, withRentalListing = false) {
  const suffix = randomUUID(); const password = "NestyStay1";
  const managerEmail = `m5-blockers-${suffix}@nestystay.local`; const ownerEmail = `m5-owner-${suffix}@nestystay.local`; const guestEmail = `m5-guest-${suffix}@nestystay.local`;
  const register = async (email: string, displayName: string, role: string) => { const response = await api.post("/api/auth/register", { data: { email, password, confirmPassword: password, displayName, acceptedTerms: true, acceptedPrivacy: true, role } }); expect(response.ok(), await response.text()).toBeTruthy(); return response.json(); };
  await register(managerEmail, "M5 release manager", "PropertyManager"); const owner = await register(ownerEmail, "M5 release owner", withRentalListing ? "Host" : "Owner"); const guest = await register(guestEmail, "M5 release guest", "Guest");
  const managerLogin = await api.post("/api/auth/login", { data: { email: managerEmail, password } }); expect(managerLogin.ok(), await managerLogin.text()).toBeTruthy(); const managerHeaders = { Authorization: `Bearer ${(await managerLogin.json()).accessToken}` };
  const ownerLogin = await api.post("/api/auth/login", { data: { email: ownerEmail, password } }); expect(ownerLogin.ok(), await ownerLogin.text()).toBeTruthy(); const ownerToken = (await ownerLogin.json()).accessToken as string; const ownerHeaders = { Authorization: `Bearer ${ownerToken}` };
  await expect.poll(async () => (await api.post("/api/property-manager/owners", { headers: managerHeaders, data: { email: ownerEmail, displayName: "M5 release owner" } })).ok()).toBeTruthy();
  const managed = await api.post("/api/property-manager/properties", { headers: managerHeaders, data: { ownerUserId: owner.userId, title: "M5 release apartment", unitNumber: `M5-${suffix.slice(0, 6)}`, address: "Kingston" } }); expect(managed.ok(), await managed.text()).toBeTruthy(); const propertyId = (await managed.json()).id as string;
  let listingId: string | undefined;
  if (withRentalListing) { const listing = await api.post("/api/properties", { headers: ownerHeaders, data: { hostUserId: owner.userId, hostName: "M5 release owner", hostEmail: ownerEmail, title: `M5 rental ${suffix}`, location: "Kingston", country: "Jamaica", nightlyRate: 100, currency: "JMD", badgeLevel: "Free", cancellationPolicy: "Flexible" } }); expect(listing.ok(), await listing.text()).toBeTruthy(); listingId = (await listing.json()).id as string; }
  return { suffix, password, managerEmail, ownerEmail, guestEmail, ownerId: owner.userId as string, guestId: guest.userId as string, propertyId, managerHeaders, ownerHeaders, listingId };
}

async function login(page: Page, email: string, password: string) {
  await page.goto("/login"); const form = page.locator("form").filter({ has: page.getByRole("heading", { name: "Log in", exact: true }) }); await form.getByLabel("Email", { exact: true }).fill(email); await form.getByLabel("Password", { exact: true }).fill(password); const response = page.waitForResponse(item => item.url().endsWith("/api/auth/login") && item.request().method() === "POST"); await form.getByRole("button", { name: /log in/i }).click(); expect((await response).ok()).toBeTruthy();
}

test("M5 reservation amendment cancellation rebooking and calendar are usable", async ({ page, request }) => {
  const data = await prepare(request, true);
  const linked = await request.patch(`/api/property-manager/properties/${data.propertyId}/rental-listing`, { headers: data.managerHeaders, data: { rentalListingId: data.listingId! } }); expect(linked.ok(), await linked.text()).toBeTruthy();
  const booking = await request.post("/api/bookings", { headers: { Authorization: `Bearer ${await tokenFor(request, data.guestEmail, data.password)}` }, data: { propertyId: data.listingId!, guestUserId: data.guestId, checkIn: isoDay(4), checkOut: isoDay(6) } }); expect(booking.ok(), await booking.text()).toBeTruthy(); const bookingId = (await booking.json()).id as string;
  await login(page, data.managerEmail, data.password); await page.goto("/pm/operations");
  const reservation = page.locator(`#reservation-${bookingId}`); await expect(reservation).toBeVisible(); await reservation.getByLabel("New check-in").fill(isoDay(7)); await reservation.getByLabel("New check-out").fill(isoDay(9)); await reservation.getByLabel("Reason").fill("Guest confirmed revised dates"); await reservation.getByRole("button", { name: "Preview amendment" }).click(); await expect(reservation.getByText(/Available/)).toBeVisible(); await reservation.getByRole("button", { name: "Confirm amendment" }).click(); await expect(page.getByText("Reservation amendment confirmed", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Master calendar" }).click(); await expect(page.locator("span.font-semibold").filter({ hasText: /^RESERVATION$/ }).first()).toBeVisible(); await expect(page.getByText(/server-calculated overlap warnings/i)).toBeVisible();
  await page.getByRole("button", { name: "Reservations", exact: true }).click(); const amended = page.locator(`#reservation-${bookingId}`); await amended.getByLabel("Reason").fill("Guest requested cancellation"); await amended.getByRole("button", { name: "Cancel reservation" }).click(); await expect(page.getByText("Reservation cancelled", { exact: true })).toBeVisible();
  const cancelled = page.locator(`#reservation-${bookingId}`); await cancelled.getByLabel("Replacement check-in").fill(isoDay(10)); await cancelled.getByLabel("Replacement check-out").fill(isoDay(12)); await cancelled.getByLabel("Reason").fill("Replacement dates approved"); await cancelled.getByRole("button", { name: "Create replacement reservation" }).click(); await expect(page.getByText("Replacement reservation created", { exact: true })).toBeVisible();
});

test("M5 owner approval decision and immutable history are usable", async ({ page, request }) => {
  const data = await prepare(request); const approval = await request.post("/api/property-manager/p0/approvals", { headers: data.managerHeaders, data: { ownerUserId: data.ownerId, propertyId: data.propertyId, approvalType: "MAINTENANCE", description: "Replace failed water heater", amount: 125, currency: "JMD", expiresAt: new Date(Date.now() + 86400000).toISOString(), idempotencyKey: `browser-approval-${data.suffix}` } }); expect(approval.ok(), await approval.text()).toBeTruthy();
  await login(page, data.ownerEmail, data.password); await page.goto("/owner/p0"); await expect(page.getByText("Replace failed water heater", { exact: true })).toBeVisible(); await page.getByLabel("Decision reason").fill("Evidence and quote reviewed"); await page.getByRole("button", { name: "Approve", exact: true }).click(); await expect.poll(async () => (await request.get("/api/property-manager/p0/owner/portal", { headers: data.ownerHeaders }).then(response => response.json())).approvals.find((item: { description: string }) => item.description === "Replace failed water heater")?.status).toBe("APPROVED");
});

test("M5 maintenance receipts corrections and corrective readiness are usable", async ({ page, request }) => {
  const data = await prepare(request); const created = await request.post("/api/property-manager/professional/maintenance", { headers: data.managerHeaders, data: { ownerUserId: data.ownerId, propertyId: data.propertyId, title: "Repair entry latch", description: "Latch failed inspection" } }); expect(created.ok(), await created.text()).toBeTruthy(); const maintenance = await created.json();
  const approval = await request.post("/api/property-manager/p0/approvals", { headers: data.managerHeaders, data: { ownerUserId: data.ownerId, propertyId: data.propertyId, approvalType: "MAINTENANCE", description: "Approve latch repair", amount: 200, currency: "JMD", sourceType: "MAINTENANCE", sourceId: maintenance.id, idempotencyKey: `browser-maintenance-approval-${data.suffix}` } }); expect(approval.ok(), await approval.text()).toBeTruthy(); const approvalBody = await approval.json(); const decision = await request.post(`/api/property-manager/p0/approvals/${approvalBody.id}/decision`, { headers: data.ownerHeaders, data: { status: "APPROVED", reason: "Repair authorized", rowVersion: approvalBody.rowVersion, idempotencyKey: `browser-maintenance-decision-${data.suffix}` } }); expect(decision.ok(), await decision.text()).toBeTruthy();
  await login(page, data.managerEmail, data.password); await page.goto("/pm/operations?tab=maintenance"); await page.getByText(maintenance.number, { exact: false }).first().waitFor();
  const upload = page.locator("input[type=file]").first(); await upload.setInputFiles({ name: "receipt.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4\n") }); await expect(page.getByText("Maintenance evidence uploaded", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "View evidence" }).click();
  const financeCard = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Receipts, classified costs and corrections" }) }); await financeCard.getByLabel("Description", { exact: true }).fill("Latch repair labour"); await financeCard.getByLabel("Amount", { exact: true }).fill("120"); await financeCard.getByLabel(`Receipt for ${maintenance.number}`).selectOption({ label: "receipt.pdf" }); await financeCard.getByRole("button", { name: "Add cost to this case" }).click(); await expect(page.getByText("Maintenance cost line saved", { exact: true })).toBeVisible();
  await page.getByLabel("Approved owner decision (when required)").selectOption(approvalBody.id); for (const status of ["TRIAGED", "OWNER_APPROVAL", "ASSIGNED", "SCHEDULED", "IN_PROGRESS", "COMPLETED"]) { await page.getByLabel(`Maintenance state ${maintenance.number}`).selectOption(status); await expect(page.getByText("Maintenance state updated", { exact: true })).toBeVisible(); }
  await expect(page.getByText(/POSTED/).first()).toBeVisible(); await financeCard.getByText("Correct posted financials", { exact: true }).click(); await financeCard.getByLabel("Correct total").fill("110"); await financeCard.getByLabel("Correct owner charge").fill("100"); await financeCard.getByLabel("Manager fee").fill("0"); await financeCard.getByLabel("Correction reason").fill("Vendor credit received"); await financeCard.getByRole("button", { name: "Post reversal and replacement" }).click(); await expect(page.getByText("Financial correction posted as reversal and replacement", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Readiness" }).click(); await page.getByLabel("Due at").fill(`${isoDay(2)}T10:00`); await page.getByRole("button", { name: "Create readiness task" }).click(); await expect(page.getByText("Readiness task created from a versioned checklist snapshot", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "Mark READY" }).last().click(); await expect(page.getByRole("alert")).toContainText("Required checklist items"); await page.getByRole("button", { name: "Complete required items" }).last().click(); await page.getByRole("button", { name: "Mark READY" }).last().click(); await expect(page.getByText("Readiness marked ready", { exact: true })).toBeVisible();
});

test("M5 inspection failure corrective work and reinspection are usable", async ({ page, request }) => {
  const data = await prepare(request);
  const template = await request.post("/api/property-manager/professional/checklist-templates", { headers: data.managerHeaders, data: { name: "Browser safety", workflowType: "INSPECTION", itemsJson: "[{\"id\":\"gate\",\"label\":\"Gate secured\",\"required\":true,\"completed\":false}]" } }); expect(template.ok(), await template.text()).toBeTruthy();
  const templateId = (await template.json()).id as string;
  const assigned = await request.put(`/api/property-manager/professional/properties/${data.propertyId}/checklist-template`, { headers: data.managerHeaders, data: { templateId } }); expect(assigned.ok(), await assigned.text()).toBeTruthy();
  await login(page, data.managerEmail, data.password); await page.goto("/pm/operations?tab=inspections");
  await page.getByLabel("Scheduled at").fill(`${isoDay(3)}T10:00`); await page.getByLabel("Failed finding / corrective scope").fill("Gate latch is unsafe"); await page.getByRole("button", { name: "Schedule inspection" }).click(); await expect(page.getByText("Inspection scheduled", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Record failed item" }).click(); await expect(page.getByText("Inspection failed and corrective action opened", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Create corrective work order" }).first().click(); await expect(page.getByText("Corrective work order created", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Work orders", exact: true }).click(); const workOrderState = page.locator('select[aria-label^="Work order state"]').first(); for (const status of ["QUOTING", "ASSIGNED", "SCHEDULED", "IN_PROGRESS", "COMPLETED"]) { await workOrderState.selectOption(status); await expect(page.getByText("Work order updated", { exact: true })).toBeVisible(); }
  await page.getByRole("button", { name: "Inspections", exact: true }).click();
  await page.getByRole("button", { name: "Request reinspection" }).click(); await expect(page.getByText("Corrective action updated", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Schedule reinspection" }).click(); await expect(page.getByText("Reinspection scheduled", { exact: true })).toBeVisible();
  const inspectionsResponse = await request.get(`/api/property-manager/professional/inspections?propertyId=${data.propertyId}`, { headers: data.managerHeaders }); const inspections = await inspectionsResponse.json(); const reinspection = inspections.find((item: { inspectionType: string }) => item.inspectionType === "REINSPECTION"); expect(reinspection).toBeTruthy(); await page.locator(`select[aria-label="Inspection status ${reinspection.id}"]`).selectOption("SIGNED_OFF"); await expect(page.getByText("Inspection status updated", { exact: true })).toBeVisible();
  await expect.poll(async () => { const response = await request.get("/api/property-manager/professional/corrective-actions", { headers: data.managerHeaders }); const items = await response.json(); return items.some((item: { status: string }) => item.status === "RESOLVED"); }).toBeTruthy();
});

async function tokenFor(api: APIRequestContext, email: string, password: string) { const response = await api.post("/api/auth/login", { data: { email, password } }); expect(response.ok(), await response.text()).toBeTruthy(); return (await response.json()).accessToken as string; }
